"""first migration

Revision ID: 826476c3eb2b
Revises: 
Create Date: 2024-08-08 14:00:19.751543

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '826476c3eb2b'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('enrollments',
    sa.Column('invoice_id', sa.Uuid(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('expired_at', sa.DateTime(), nullable=False),
    sa.Column('plan', sa.JSON(), nullable=True),
    sa.Column('on_item', sa.String(), nullable=True),
    sa.Column('resources', sa.JSON(), nullable=True),
    sa.Column('remain_resources', sa.JSON(), nullable=True),
    sa.Column('business_id', sa.Uuid(), nullable=False),
    sa.Column('owner_id', sa.Uuid(), nullable=False),
    sa.Column('uid', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('uid')
    )
    op.create_index(op.f('ix_enrollments_business_id'), 'enrollments', ['business_id'], unique=False)
    op.create_index(op.f('ix_enrollments_created_at'), 'enrollments', ['created_at'], unique=False)
    op.create_index(op.f('ix_enrollments_expired_at'), 'enrollments', ['expired_at'], unique=False)
    op.create_index(op.f('ix_enrollments_invoice_id'), 'enrollments', ['invoice_id'], unique=False)
    op.create_index(op.f('ix_enrollments_owner_id'), 'enrollments', ['owner_id'], unique=False)
    op.create_index(op.f('ix_enrollments_started_at'), 'enrollments', ['started_at'], unique=False)
    op.create_index(op.f('ix_enrollments_uid'), 'enrollments', ['uid'], unique=True)
    op.create_table('usages',
    sa.Column('enrollment_id', sa.Uuid(), nullable=False),
    sa.Column('resource', sa.String(), nullable=False),
    sa.Column('volume', sa.Integer(), nullable=False),
    sa.Column('on_item', sa.String(), nullable=False),
    sa.Column('uid', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['enrollment_id'], ['enrollments.uid'], ),
    sa.PrimaryKeyConstraint('uid')
    )
    op.create_index(op.f('ix_usages_created_at'), 'usages', ['created_at'], unique=False)
    op.create_index(op.f('ix_usages_enrollment_id'), 'usages', ['enrollment_id'], unique=False)
    op.create_index(op.f('ix_usages_on_item'), 'usages', ['on_item'], unique=False)
    op.create_index(op.f('ix_usages_resource'), 'usages', ['resource'], unique=False)
    op.create_index(op.f('ix_usages_uid'), 'usages', ['uid'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_usages_uid'), table_name='usages')
    op.drop_index(op.f('ix_usages_resource'), table_name='usages')
    op.drop_index(op.f('ix_usages_on_item'), table_name='usages')
    op.drop_index(op.f('ix_usages_enrollment_id'), table_name='usages')
    op.drop_index(op.f('ix_usages_created_at'), table_name='usages')
    op.drop_table('usages')
    op.drop_index(op.f('ix_enrollments_uid'), table_name='enrollments')
    op.drop_index(op.f('ix_enrollments_started_at'), table_name='enrollments')
    op.drop_index(op.f('ix_enrollments_owner_id'), table_name='enrollments')
    op.drop_index(op.f('ix_enrollments_invoice_id'), table_name='enrollments')
    op.drop_index(op.f('ix_enrollments_expired_at'), table_name='enrollments')
    op.drop_index(op.f('ix_enrollments_created_at'), table_name='enrollments')
    op.drop_index(op.f('ix_enrollments_business_id'), table_name='enrollments')
    op.drop_table('enrollments')
    # ### end Alembic commands ###
