"""usage bus owned entity

Revision ID: be965c9c535e
Revises: 826476c3eb2b
Create Date: 2024-08-08 19:03:37.626214

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'be965c9c535e'
down_revision: Union[str, None] = '826476c3eb2b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usages', sa.Column('business_id', sa.Uuid(), nullable=False))
    op.add_column('usages', sa.Column('owner_id', sa.Uuid(), nullable=False))
    op.create_index(op.f('ix_usages_business_id'), 'usages', ['business_id'], unique=False)
    op.create_index(op.f('ix_usages_owner_id'), 'usages', ['owner_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_usages_owner_id'), table_name='usages')
    op.drop_index(op.f('ix_usages_business_id'), table_name='usages')
    op.drop_column('usages', 'owner_id')
    op.drop_column('usages', 'business_id')
    # ### end Alembic commands ###
